# Specify the AWS region code
# bora will attempt to get it from AWS configuration
# or from the environment. This setting overrides
# every other. 
region: "eu-central-1"

# Required: specify the name of the stack
# (bora will look for a template under templates/
# that matches the stack name
stackname: "test-sqs-thingy"

# Stack-specific variables
# You can define arbitrary keys in here, 
# *except* for the top-level CF key, which 
# bora requires. 
CF:
  Queues:
    - QueueName: "pierwsza"
    - QueueName: "druga"
